name: CI

on:
  push:
    branches:
      - master
      - 'v8.13'
  pull_request:
    branches:
      - '**'
  schedule:
    # test master every day at 04:00 UTC
      - cron: '0 4 * * *'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:dev'
          - 'coqorg/coq:8.13'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-bignums.opam'
          custom_image: ${{ matrix.image }}
          export: 'OPAMWITHTEST'
        env:
          OPAMWITHTEST: 'true'

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
