# Beware not to destroy this file when regenerating it from meta.yml

name: Docker CI

on:
  # schedule:
  #   - cron: '0 4 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - 'dev'
        image:
          # we can't use coqorg/coq images to test bignums
          # since these images already include coq-bignums
          - 'coqorg/base:4.13.1-flambda'
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-bignums.opam'
          custom_image: ${{ matrix.image }}
          install: |
            startGroup "Install"
              sudo apt-get update -y -q
              opam remove -y coq-bignums || true # remove coq-bignums if ever in image
              opam repository add --all-switches --set-default coq-extra-dev https://coq.inria.fr/opam/extra-dev # docker-coq
              opam repository add --all-switches --set-default coq-core-dev https://coq.inria.fr/opam/core-dev # docker-coq
              opam pin add -n -y -k version coq ${{ matrix.coq_version }} # docker-coq
              opam pin add -n -y -k path rocq-bignums.dev $WORKDIR
              opam pin add -n -y -k path coq-bignums.dev $WORKDIR
              opam update -y
              opam install --confirm-level=unsafe-yes -j 2 rocq-bignums --ignore-constraints-on=dune
              opam install --confirm-level=unsafe-yes -j 2 coq-bignums --ignore-constraints-on=dune
            endGroup
          script: |
            startGroup "Post install"
              opam list
            endGroup
          export: 'OPAMWITHTEST'
        env:
          OPAMWITHTEST: 'true'

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
