# Beware not to destroy this file when regenerating it from meta.yml

name: Docker CI

on:
  # schedule:
  #   - cron: '0 4 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:dev'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-bignums.opam'
          custom_image: ${{ matrix.image }}
          install: |
            startGroup "Install dependencies"
              # sudo apt-get update -y -q
              opam remove -y coq-bignums # remove coq-bignums already in image
              opam pin add -n -y -k path $PACKAGE $WORKDIR
              opam update -y
              opam install --confirm-level=unsafe-yes -j 2 $PACKAGE --deps-only
            endGroup
          export: 'OPAMWITHTEST'
        env:
          OPAMWITHTEST: 'true'

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
